### PR TITLE
change classic-watchdog to of-watchdog & swap port 8081 -> 8082

### LINKED ISSUE #3: listener on 8081 already in use.
TCP socket 8081 appears to already be in use when posting to the handler. Could this be conflicting with the metrics API?

```
2019/10/12 00:27:39 Version: 0.18.0	SHA: 137b63e61fe55e0aea7df466931198c37817f743
2019/10/12 00:27:39 Timeouts: read: 5s, write: 5s hard: 0s.
2019/10/12 00:27:39 Listening on port: 8080
2019/10/12 00:27:39 Writing lock-file to: /tmp/.lock
2019/10/12 00:27:39 Metrics listening on port: 8081
~ $ kubectl logs -n openfaas-fn faas-gpoacl-create-6ff889b5dc-7ml2z -f
2019/10/12 00:27:39 Version: 0.18.0	SHA: 137b63e61fe55e0aea7df466931198c37817f743
2019/10/12 00:27:39 Timeouts: read: 5s, write: 5s hard: 0s.
2019/10/12 00:27:39 Listening on port: 8080
2019/10/12 00:27:39 Writing lock-file to: /tmp/.lock
2019/10/12 00:27:39 Metrics listening on port: 8081
2019/10/12 00:28:08 Forking fprocess.
2019/10/12 00:28:08 Query
2019/10/12 00:28:08 Path  /
2019/10/12 00:28:09 Duration: 0.632475 seconds
Exception calling "Start" with "0" argument(s): "Address already in use"
At /server.ps1:20 char:1
+ $listener.Start()
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : HttpListenerException

Exception calling "GetContext" with "0" argument(s): "Cannot access a disposed object.
Object name: 'System.Net.HttpListener'."
At /server.ps1:25 char:5
+     $context = $listener.GetContext()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : ObjectDisposedException
```

https://github.com/openfaas-incubator/powershell-http-template/blob/c671be521f1f4e575ea726f8c2a39b58f69b3107/template/powershell-http/server.ps1#L19

### PR DESCRIPTION
**Pull request by MnrGreg**
change classic-watchdog to of-watchdog
change upstream port from 8081 to 8082

fixes #3

### CODE REVIEW

**Comment by alexellis** [comment]
This change needs to be signed-off. Please run:

```
git commit --amend -s
git push origin master --force
```

**Comment by alexellis** [comment]
Once signed-off, please provide evidence of testing - command-line output or a screenshot.

**Comment by MnrGreg** [comment]
Evidence of testing:

Post / Response:
```
$ curl -d 'Hello World' https://openfaas.services.west.nonprod.[redacted].com/function/faas-powershell-http
Hello! Your input was: Hello World
```

Container log:
```
$ kubectl logs -n openfaas-fn faas-powershell-http-969f5bf85-8wldv
2019/10/22 05:03:05 Started logging stderr from function.
2019/10/22 05:03:05 Started logging stdout from function.
Forking - pwsh [server.ps1]
2019/10/22 05:03:05 OperationalMode: http
2019/10/22 05:03:05 Timeouts: read: 10s, write: 10s hard: 10s.
2019/10/22 05:03:05 Listening on port: 8080
2019/10/22 05:03:05 Writing lock-file to: /tmp/.lock
2019/10/22 05:03:05 Metrics listening on port: 8081
2019/10/22 05:03:22 POST / - 200 OK - ContentLength: 34
```

**Review by alexellis — APPROVED** [review]
Approved, LGTM

**Comment by alexellis** [comment]
Thank you so much 💪 

cc @burtonr

**Comment by burtonr** [comment]
Nice work! Thank you @MnrGreg  :100:

**Pull request merged**
